TrajectoryPlannerROS:
  #Robot Configuration Parameters
  max_vel_x: 0.35
  min_vel_x: 0.1

  max_vel_theta: 1.5
  min_vel_theta: -1.0 #-1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  #Goal Tolerance Parameters
  yaw_goal_tolerance: 1.0 #0.05
  acc_xy_goal_tolerancelim_x: 0.50 #0.10

  #Forward Simulation Parameters
  sim_time: 1.0 #1.0
  sim_granularity: 0.025 #0.025
  vx_samples: 3 #3 
  vtheta_samples: 20 #20

  controller_frequency: 8 #20  

  #Trajectory Scoring Parameters
  meter_scoring: false #false
  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.01 #0.01
  heading_lookahead: 0.325 #-.325
  heading_scoring: false #false
  heading_scoring_timestep: 0.8 #0.8
  dwa: true #true
  oscillation_reset_dist: 0.05 #0.05
